/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadorav;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Nick
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        cmb_clase = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmb_raza = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_mana = new javax.swing.JTextField();
        txt_vida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora CoverAO");
        setName("Calculadora CoverAO"); // NOI18N
        setResizable(false);

        cmb_clase.setBackground(new java.awt.Color(51, 51, 51));
        cmb_clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mago", "Clerigo", "Nigromante", "Druida", "Bardo", "Asesino", "Guerrero", "Mercenario", "Ladron", "Cazador", "Paladin" }));
        cmb_clase.setToolTipText("");
        cmb_clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_claseActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clase");

        cmb_raza.setBackground(new java.awt.Color(51, 51, 51));
        cmb_raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gnomo", "Elfo", "Elfo Drow", "Humano", "Orco", "Enano" }));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Raza");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_mana.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        txt_vida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_vida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vidaActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MANA MAX");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VIDA MAX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_clase, 0, 230, Short.MAX_VALUE)
                            .addComponent(cmb_raza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_mana, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_clase))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_raza))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_vidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vidaActionPerformed

    private void cmb_claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_claseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_claseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Vida;
String Mana;

//************************************* CLERIGO***********************************//
       if(cmb_clase.getSelectedItem() == "Clerigo" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "360";
    Mana = "2206";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Clerigo" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "372";
    Mana = "2108";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Clerigo" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "386";
    Mana = "2010";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Clerigo" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "404";
    Mana = "1912";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Clerigo" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "423";
    Mana = "1324";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Clerigo" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "448";
    Mana = "1324";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

} //****************************************MAGO*****************************************//
       else if(cmb_clase.getSelectedItem() == "Mago" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "321";
    Mana = "3284";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}  else  if(cmb_clase.getSelectedItem() == "Mago" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "330";
    Mana = "3125";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Mago" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "344";
    Mana = "2957";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Mago" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "361";
    Mana = "2854";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Mago" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "376";
    Mana = "1803";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Mago" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "388";
    Mana = "1803";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
///*******************************NIGROMANTE******************************************//
else  if(cmb_clase.getSelectedItem() == "Nigromante" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "346";
    Mana = "2745";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Nigromante" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "354";
    Mana = "2598";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Nigromante" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "363";
    Mana = "2650";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Nigromante" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "382";
    Mana = "2402";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Nigromante" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "388";
    Mana = "1618";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Nigromante" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "431";
    Mana = "1618";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //********************************DRUIDA***********************************//
       else  if(cmb_clase.getSelectedItem() == "Druida" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "350";
    Mana = "2206";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Druida" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "362";
    Mana = "2108";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Druida" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "375";
    Mana = "2010";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Druida" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "394";
    Mana = "1912";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Druida" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "413";
    Mana = "1324";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Druida" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "438";
    Mana = "1324";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //**************************************BARDO*********************************//
       else  if(cmb_clase.getSelectedItem() == "Bardo" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "350";
    Mana = "2206";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Bardo" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "362";
    Mana = "2108";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Bardo" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "376";
    Mana = "2010";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Bardo" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "393";
    Mana = "1912";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Bardo" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "413";
    Mana = "1324";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Bardo" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "438";
    Mana = "1324";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //******************************ASESINO**********************//
       else  if(cmb_clase.getSelectedItem() == "Asesino" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "370";
    Mana = "1128";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Asesino" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "394";
    Mana = "1079";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Asesino" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "412";
    Mana = "1040";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Asesino" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "428";
    Mana = "981";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Asesino" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "446";
    Mana = "687";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Asesino" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "462";
    Mana = "687";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //********************************GUERRERO****************************//
       else  if(cmb_clase.getSelectedItem() == "Guerrero" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "460";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Guerrero" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "484";
     Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Guerrero" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "498";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Guerrero" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "516";
      Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Guerrero" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "528";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Guerrero" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "528";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //**************************************GLADIADOR**************************//
       else  if(cmb_clase.getSelectedItem() == "Gladiador" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "411";
    Mana = "3284";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Gladiador" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "436";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Gladiador" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "461";
       Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Gladiador" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "486";
      Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Gladiador" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "492";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Gladiador" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "492";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //**************************************MERCENARIO************************//
       else  if(cmb_clase.getSelectedItem() == "Mercenario" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "460";
     Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Mercenario" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "472";
      Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Mercenario" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "478";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Mercenario" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "511";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Mercenario" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "517";
      Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Mercenario" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "517";
       Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //*****************************************LADRON*******************************//
       else  if(cmb_clase.getSelectedItem() == "Ladron" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "338";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Ladron" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "374";
     Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Ladron" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "388";
    Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Ladron" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "412";
     Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Ladron" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "435";
     Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Ladron" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "438";
      Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //*****************************************CAZADOR*****************************//
       else  if(cmb_clase.getSelectedItem() == "Cazador" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "460";
       Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Cazador" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "472";
     Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Cazador" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "486";
     Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Cazador" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "498";
      Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Cazador" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "511";
       Mana = "Clase sin mana";

    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Cazador" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "511";
    Mana = "Clase sin mana";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       //****************************************PALADIN********************************//
       else  if(cmb_clase.getSelectedItem() == "Paladin" && cmb_raza.getSelectedItem() == "Gnomo"){
    Vida = "448";
    Mana = "1078";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
        else  if(cmb_clase.getSelectedItem() == "Paladin" && cmb_raza.getSelectedItem() == "Elfo"){
    Vida = "460";
    Mana = "1029";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Paladin" && cmb_raza.getSelectedItem() == "Elfo Drow"){
    Vida = "467";
    Mana = "980";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Paladin" && cmb_raza.getSelectedItem() == "Humano"){
    Vida = "478";
    Mana = "931";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Paladin" && cmb_raza.getSelectedItem() == "Orco"){
    Vida = "494";
    Mana = "660";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}else  if(cmb_clase.getSelectedItem() == "Paladin" && cmb_raza.getSelectedItem() == "Enano"){
    Vida = "499";
    Mana = "633";
    txt_mana.setText(Mana);
    txt_vida.setText(Vida);

}
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_clase;
    private javax.swing.JComboBox<String> cmb_raza;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_mana;
    private javax.swing.JTextField txt_vida;
    // End of variables declaration//GEN-END:variables


class FondoPanel extends JPanel{
                
                
                private Image imagen;
                @Override
                
                public void paint(Graphics g){
                imagen = new ImageIcon(getClass().getResource("/Fondos/FondoD.jpeg")).getImage();
                g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
                setOpaque(false);
                super.paint(g);
                
                
                }
            }

}
